<a href="https://colab.research.google.com/github/lresendao/Data_Science/blob/Estatistica_I/Amostragem_Estratificada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
#Carregamento da base de dados e contagem de quantos registros existem por classe
iris = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Udemy/Python/Estatística I/iris.csv')
iris['class'].value_counts()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [ ]:
#iris.iloc[:, 0:4]: buscamos somente os atributos previsores, ou seja, os dados sobre pétala e sétala da planta
#iris.iloc[:, 4]: buscamos somente a classe, que é a espécie da planta (setosa, virginica ou versicolor)
#test_size: selecionamos 50% da base de dados, que serão copiados para as variáveis X e Y. Essa função retorna 4 valores,
#porém, vamos usar somente os 50% da base de dados e por isso colocamos "_" para outros valores
#stratify: para retornar a amostra baseada na classe
x, _, y, _ = train_test_split(iris.iloc[:, 0:4], iris.iloc[:, 4],
                              test_size = 0.5, stratify = iris.iloc[:,4])
y.value_counts()

class
Iris-setosa        25
Iris-versicolor    25
Iris-virginica     25
Name: count, dtype: int64

In [ ]:
#Carregamento da base de dados e contagem de quantos registros por classe
infert = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Udemy/Python/Estatística I/infert.csv')
infert

,Unnamed: 0,education,age,parity,induced,case,spontaneous,stratum,pooled.stratum
0,1,0-5yrs,26,6,1,1,2,1,3
1,2,0-5yrs,42,1,1,1,0,2,1
2,3,0-5yrs,39,6,2,1,0,3,4
3,4,0-5yrs,34,4,2,1,0,4,2
4,5,6-11yrs,35,3,1,1,1,5,32
...,...,...,...,...,...,...,...,...,...
243,244,12+ yrs,31,1,0,0,1,79,45
244,245,12+ yrs,34,1,0,0,0,80,47
245,246,12+ yrs,35,2,2,0,0,81,54
246,247,12+ yrs,29,1,0,0,1,82,43
247,248,12+ yrs,23,1,0,0,1,83,40

In [ ]:
infert['education'].value_counts()

education
6-11yrs    120
12+ yrs    116
0-5yrs      12
Name: count, dtype: int64

In [ ]:
#Criando uma amostra somente com 40% dos registros (por isso é definido 0.6, pois é gerado o inverso)
X1, _, y1, _ = train_test_split(infert.iloc[:, 2:9], infert.iloc[:, 1],
                                test_size = 0.6, stratify = infert.iloc[:, 1])
y1.value_counts()

education
6-11yrs    48
12+ yrs    46
0-5yrs      5
Name: count, dtype: int64